# Generated by Django 5.0.6 on 2024-10-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_editor_phone_number_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='articles/default.jpg', upload_to='articles/'),
        ),
    ]
